import datetime, sys
# Teste de ponta a ponta do ambiente do estudante (Playwright). Requer: supabase start + npm run dev (porta 5173).
# Uso: docker exec supabase_db_epf-monitor psql -U postgres -qc 'delete from participante; delete from sessao;' && python3 e2e/estudante.py /tmp
from playwright.sync_api import sync_playwright, expect
BASE = 'http://localhost:5173'
OUT = sys.argv[1]
onze = (datetime.date.today().replace(year=datetime.date.today().year - 11) - datetime.timedelta(days=1)).isoformat()
ok = []
def check(nome, cond):
    ok.append((nome, bool(cond))); print(('OK   ' if cond else 'FALHA ') + nome)

with sync_playwright() as p:
    b = p.chromium.launch()
    ctx = b.new_context(viewport={'width': 390, 'height': 844}, locale='pt-BR')
    pg = ctx.new_page()
    pg.goto(f'{BASE}/responder/teste-norte'); pg.get_by_role('heading', name='Olá!').wait_for()
    pg.screenshot(path=f'{OUT}/1-boas-vindas.png', full_page=True)
    pg.get_by_role('button', name='Começar').click()
    pg.get_by_role('button', name='Sim, aceito participar').click()
    pg.get_by_label('Nome completo').fill('Pedro Alves')
    pg.get_by_label('Sua escola').select_option(label='EM ALFA')
    pg.get_by_label('6º ano').check()
    pg.get_by_label('Data de nascimento').fill(onze)
    check('autorização aparece para menor de 12', pg.get_by_text('Você tem menos de 12 anos.').is_visible())
    pg.get_by_role('button', name='Começar o questionário').click()
    check('exige autorização', pg.get_by_text('Para responder, seu responsável precisa ter autorizado.').is_visible())
    pg.screenshot(path=f'{OUT}/2-cadastro.png', full_page=True)
    pg.get_by_text('Você tem menos de 12 anos.').click()
    pg.get_by_role('button', name='Começar o questionário').click()
    pg.get_by_text('Parte 1 de 4').wait_for()
    check('6º ano recebe 4 partes (A, B, G, I)', True)
    pg.get_by_role('button', name='Salvar e continuar').click()
    check('pendência avisada', pg.get_by_text('Responda todas as perguntas desta parte para continuar.').first.is_visible())
    pg.get_by_label('Branca').check(); pg.get_by_label('Sim').check()
    check('dependente A9_1 aparece', pg.get_by_text('De quais atividades você participa?').is_visible())
    pg.get_by_label('Música').check(); pg.get_by_label('Dança').check()
    check('3ª opção bloqueada no limite de 2', pg.get_by_label('Teatro').is_disabled())
    check('aviso de pendência some quando tudo foi respondido', not pg.get_by_text('Responda todas as perguntas desta parte para continuar.').first.is_visible())
    pg.screenshot(path=f'{OUT}/3-bloco-a.png', full_page=True)
    pg.get_by_role('button', name='Salvar e continuar').click()
    pg.get_by_text('Parte 2 de 4').wait_for()
    pg.reload(); pg.get_by_role('button', name='Continuar de onde parei').click()
    pg.get_by_text('Parte 2 de 4').wait_for()
    check('retomada na parte 2 após recarregar', pg.get_by_text('Que bom que você voltou!').is_visible())
    for fs in pg.locator('fieldset').all():
        fs.get_by_label('Concordo', exact=True).check()
    pg.screenshot(path=f'{OUT}/4-bloco-b.png', full_page=True)
    pg.get_by_role('button', name='Salvar e continuar').click()
    pg.get_by_text('Parte 3 de 4').wait_for()
    check('parte 3 é a de transição do 6º', pg.get_by_role('heading', name='Transições (6º ano)').is_visible())
    pg.get_by_label('Não').check(); pg.get_by_role('button', name='Salvar e continuar').click()
    pg.get_by_text('Parte 4 de 4').wait_for()
    pg.get_by_role('button', name='Enviar respostas').click()
    pg.get_by_role('heading', name='Obrigado por participar!').wait_for()
    check('conclusão', True)
    pg.screenshot(path=f'{OUT}/5-conclusao.png', full_page=True)

    pg2 = b.new_context(viewport={'width': 390, 'height': 844}).new_page()
    pg2.goto(f'{BASE}/responder/teste-norte'); pg2.get_by_role('button', name='Começar').click()
    pg2.get_by_role('button', name='Sim, aceito participar').click()
    pg2.get_by_label('Nome completo').fill('pedro  álves'); pg2.get_by_label('Sua escola').select_option(label='EM ALFA')
    pg2.get_by_label('6º ano').check(); pg2.get_by_label('Data de nascimento').fill(onze)
    pg2.get_by_text('Você tem menos de 12 anos.').click(); pg2.get_by_role('button', name='Começar o questionário').click()
    pg2.get_by_text('Você já respondeu esta pesquisa. Obrigado!').wait_for()
    check('não responde duas vezes (nome com outra grafia)', True)

    pg2.goto(f'{BASE}/responder/teste-sul'); pg2.get_by_text('A pesquisa está encerrada. Obrigado!').wait_for()
    check('campanha fechada', True)
    pg2.goto(f'{BASE}/responder/nao-existe'); pg2.get_by_text('Link de pesquisa não encontrado').wait_for()
    check('link inexistente', True)

    lab = b.new_context(viewport={'width': 1280, 'height': 900}).new_page()
    lab.goto(f'{BASE}/responder/teste-norte'); lab.get_by_role('heading', name='Olá!').wait_for()
    lab.screenshot(path=f'{OUT}/6-computador.png')
    b.close()
print(f'{sum(1 for _, c in ok if c)}/{len(ok)} verificações')
